name: kcc_sales_force
description: KCC Sales Force Automation Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP Client & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # Navigation
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # File & Image Handling
  image_picker: ^1.0.4
  file_picker: ^6.1.1

  # Location & Maps
  # google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  # geocoding: ^2.1.1

  # Charts & Analytics
  fl_chart: ^0.65.0

  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.0.9

  # Notifications
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  # firebase_analytics: ^10.7.4

  # Biometric Authentication
  # local_auth: ^2.1.7

  # Connectivity
  # connectivity_plus: ^5.0.2

  # Permissions
  # permission_handler: ^11.1.0

  # Utilities
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  device_info_plus: ^9.1.1

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1

  # QR & Barcode
  # qr_flutter: ^4.1.0
  # mobile_scanner: ^3.5.6

  # Camera
  # camera: ^0.10.5+5

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Testing
  integration_test:
    sdk: flutter

  # Linting & Formatting
  flutter_lints: ^3.0.1



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
