import 'package:json_annotation/json_annotation.dart';
import 'package:hive/hive.dart';
import '../../domain/entities/client.dart';
import '../../../../core/models/auth_models.dart';

part 'client_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0)
@JsonSerializable()
class ClientModel extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String? address;

  @HiveField(3)
  final double? latitude;

  @HiveField(4)
  final double? longitude;

  @HiveField(5)
  @JsonKey(name: 'balance')
  final double? balance;

  @HiveField(6)
  final String? email;

  @HiveField(7)
  @JsonKey(name: 'region_id')
  final int regionId;

  @HiveField(8)
  final String region;

  @HiveField(9)
  @JsonKey(name: 'route_id')
  final int? routeId;

  @HiveField(10)
  @JsonKey(name: 'route_name')
  final String? routeName;

  @HiveField(11)
  final String? contact;

  @HiveField(12)
  @JsonKey(name: 'tax_pin')
  final String? taxPin;

  @HiveField(13)
  final String? location;

  @HiveField(14)
  final int status;

  @HiveField(15)
  @JsonKey(name: 'client_type')
  final int? clientType;

  @HiveField(16)
  @JsonKey(name: 'outlet_account')
  final int? outletAccount;

  @HiveField(17)
  final int countryId;

  @HiveField(18)
  @JsonKey(name: 'added_by')
  final int? addedBy;

  @HiveField(19)
  @JsonKey(name: 'addedByUser')
  final SalesRep? addedByUser;

  @HiveField(20)
  @JsonKey(name: 'created_at')
  final DateTime? createdAt;

  ClientModel({
    required this.id,
    required this.name,
    this.address,
    this.latitude,
    this.longitude,
    this.balance,
    this.email,
    required this.regionId,
    required this.region,
    this.routeId,
    this.routeName,
    this.contact,
    this.taxPin,
    this.location,
    required this.status,
    this.clientType,
    this.outletAccount,
    required this.countryId,
    this.addedBy,
    this.addedByUser,
    this.createdAt,
  });

  factory ClientModel.fromJson(Map<String, dynamic> json) =>
      _$ClientModelFromJson(json);

  Map<String, dynamic> toJson() => _$ClientModelToJson(this);

  Client toEntity() {
    return Client(
      id: id,
      name: name,
      address: address,
      latitude: latitude,
      longitude: longitude,
      balance: balance,
      email: email,
      regionId: regionId,
      region: region,
      routeId: routeId,
      routeName: routeName,
      contact: contact,
      taxPin: taxPin,
      location: location,
      status: status,
      clientType: clientType,
      outletAccount: outletAccount,
      countryId: countryId,
      addedBy: addedBy,
      addedByUser: addedByUser,
      createdAt: createdAt,
    );
  }

  factory ClientModel.fromEntity(Client entity) {
    return ClientModel(
      id: entity.id,
      name: entity.name,
      address: entity.address,
      latitude: entity.latitude,
      longitude: entity.longitude,
      balance: entity.balance,
      email: entity.email,
      regionId: entity.regionId,
      region: entity.region,
      routeId: entity.routeId,
      routeName: entity.routeName,
      contact: entity.contact,
      taxPin: entity.taxPin,
      location: entity.location,
      status: entity.status,
      clientType: entity.clientType,
      outletAccount: entity.outletAccount,
      countryId: entity.countryId,
      addedBy: entity.addedBy,
      addedByUser: entity.addedByUser,
      createdAt: entity.createdAt,
    );
  }
}
